### ISSUE TITLE
Track folders as files

### ISSUE THREAD

**Issue by zippynk** [bobbybee/hw#26]
Allow the user to add a folder of files as a single file (e.g an Adobe Premiere [cue the booing] project [this is a real situation of mine]). The folder would have a default file to open when called on with `hw edit`, but the user could select to view other files as well.

**Comment by bobbybee** [comment]
This seems somewhat special case. When would this generally be used?

**Comment by zippynk** [comment]
Any time someone wanted to track an assignment using hw that required multiple files associated with the same assignment, but didn't want to fully give it it's own git repo independent of hw. Amongst other things, this is the case for files involving Audacity, Logic, Premiere, and Computer Code®.

**Comment by zippynk** [comment]
(Yes, Logic can make multiple files look like one file, but underneath, it's still multiple files)

**Comment by bobbybee** [comment]
These examples seem to go against much of the motivation for `hw`. Minimal integration could be implemented for individual file formats (as is the case for LibreOffice prinintg), but in general I'm wary of this type of issue.

**Comment by zippynk** [comment]
It's not integration for a specific file format, but rather, support for treating multiple files as one file (which many different file formats require, and some project types lend themselves to).

**Comment by zippynk** [comment]
Essentially, if you're trying to create a file management system, you may not want to add tons of support for all types of files, but at least make sure that it can manage all types of files generically on a basic level.

**Comment by bobbybee** [comment]
How would the git semantics work for this? What about publishing?

**Comment by zippynk** [comment]
Publish bare, but warn first. Give each tracked folder it's own git repository within the larger one?

**Comment by bobbybee** [comment]
Perhaps it should be zipped or something first?

**Comment by zippynk** [comment]
Edited in mind-reading acknowledgement

**Comment by zippynk** [comment]
Closing for now. Go to class and pay attention.
