### ISSUE TITLE
Plaintext

### ISSUE THREAD

**Issue by zippynk** [bobbybee/hw#3]
19:08 <+nkf1> 1) stop telling me to use double-return
19:08 <+nkf1> 2) stop telling me to use some syntax to signal a single return
19:09 <+nkf1> 3) STOP TELLING ME TO USE DOUBLE RETURN GOSHDARNIT

**Comment by bobbybee** [comment]
Fair enough. I've implemented an experimental solution for this in the `plaintext` branch. Try it out; the format name is "plaintext", which you can use either via the `--format` command-line option or the `defaultFormat` configuration option.

If you like it, I'll merge it :smile:
